name: dart_server
description: A sample command-line application
dependencies:
  postgresql: any
  start:
    git: git://github.com/sethladd/start.git
  web_ui: any
  query_string: any

#dependencies:
#  unittest: any